---
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - env
      - ls -la
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=862724539066.dkr.ecr.ap-northeast-1.amazonaws.com/nichiden-backend-import
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - TIMESTAMP=$(date -u +'%Y%m%d%H%M%SZ')
      - IMAGE_TAG=$TIMESTAMP-${COMMIT_HASH:=latest}-ci
      # According to "imageDetail.json File for Amazon ECS Blue/Green Deployment Actions"
      # The imageDetail.json has to be located at build artifact /imageDetail.json and cannot be located in a sub directory.
      - printf "{\"ImageURI\":\"$REPOSITORY_URI:$IMAGE_TAG\"}" > imageDetail.json
      - cd import
  build:
    commands:
      - ls -l .
      - docker build --build-arg ENV_CONFIG_PATH=env.ci -f Dockerfile.pipeline -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - env
      - ls -la
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - imageDetail.json
    - import/appspec.yaml
    - import/taskdef-ci.json
